### PR TITLE
Broaden regex for domain validation

### PR DESCRIPTION
**Pull request by jlhonora**
Change the regex used in the Logo API url builder. I'm open to discuss other regex matchers, since matching domains can get pretty complex.

Also added some tests to check behavior.

### CODE REVIEW

**Comment by maccman** [comment]
Hmm, might be even better just removing the regex and doing validation Clearbit side. What do you think?

**Comment by jlhonora** [comment]
From Clearbit's perspective I think it is desirable to keep bad requests due to malformed domains as low as possible. If you can catch them early on without hitting your servers, great. But I guess it's up to you :)

Do you perform any domain validation server-side? If so, what's the regex used there?

**Comment by jlhonora** [comment]
Perhaps it could written as a method option, but once again, it's up to you.

**Comment by harlow** [comment]
> Do you perform any domain validation server-side? If so, what's the regex used there?

We have a private repo w/ Email, Domain, etc validators. We could potentially open-source that repo if we wanted to use it in the Gem too. @maccman thoughts?

**Comment by chamnap** [comment]
I face the problem with domain contains dash. I think this PR would solve problem. Can it be merged for the moment? Then, you guys can think about refactoring it later. :)

**Comment by maccman** [comment]
I'd rather keep as much validation server side as possible so we don't have too much business logic in the clients. Much easier to change if it's all in one place. We also have a ton of other ways we validate domains that don't fit into this regex.

**Comment by robholland** [comment]
@jlhonora Sorry for not getting this landed, can you please update the PR to just add dashes to the character sets rather than trying to enforce only a single dash at a time? We'll handle the stricter validation server side.

**Comment by jlhonora** [comment]
@robholland no worries! Added dashes to the character set.

Feel free to close this if you'll be handling it server side. I opened the PR in first place because there were valid domains that were causing argument errors, so it was kind of urgent to change it.

**Comment by robholland** [comment]
I've merged and tweaked this. Thanks for filing the PR :)

**Pull request merged**
